### ISSUE TITLE
a question about app wrapping, golden_toolkit

### ISSUE THREAD

**Issue by fredgrott** [eBay/flutter_glove_box#106]
Hello eBay,

I'm one of the contributors to the flutter platform widgets plugin, 
https://github.com/stryder-dev/flutter_platform_widgets

As part of the process of improving the docs for that plugin, I am looking at how to make it work with goldens-toolkit.

I know you might know the flutter platform widgets plugin just yet as we will not become dominant until we et full testing into our plugin. However, on the dev app side, it would seem that to integrated with using flutter platform widgets I need to customize the widget wrapper so it loads the fluter platform widgets tree of PlatformProvider, and PlatformApp and have it set app target platform. That way when it targets android I pick up the right android themes and when it targets ios I pick up the right cupertino themes as flutter platform widgets rely upon platform provider to help set up themes, localizations, etc are supplied to the app widget part.

Would that be the right way to do it knowing your full code base or would there be a better way?

Thanks for making a very useful plugin!

**Comment by coreysprague** [comment]
Yes that would be the correct way. In our application's tests, we often override the app wrapper to inject mocks or other common setup for a package. 

Since you are working on a middleware package, I would suggest considering a way to parameterize the wrapping so consumers can get your necessary widgets, but also have a means to inject their own. Hope it works out!
