### ISSUE TITLE
Investigate auto-sizing the surfaceSize before capturing the golden.

### ISSUE THREAD

**Issue by coreysprague** [eBay/flutter_glove_box#13]
Right now, it is possible to capture golden screenshots that exceed the dimensions of the target device size. This is valuable for asserting that all content looks correct, without the need for scrolling. However, doing this often requires manual overriding of the golden size. As widgets change, this override requires micro-management. Additionally, if the overridden size is much larger than the content, then the captured golden is large and full of dead space.

We should investigate if we can compute the size needed and shrink the surface size accordingly. 

I suspect this will require additional pumps and likely add latency to the golden assertion. Assuming this is the case, we should consider this an opt-in feature and still allow for fine-grained sizing.

**Comment by christian-muertz** [comment]
I am currently facing:

1. Sth. like a ListView which should be full visible in the golden file
2. A widget that is not as large as the screen which adds a lot of whitespace to the bottom of the file

Ideas

1) There should be a prop like `autoSize` which finds the main scrollable and adjusts the surface size accordingly. This is non trivial because its not obvious which scrollable is the main one (Maybe just use the first vertical scrollable?)

2) If the targetted widget is smaller then the devices surface there should be an easy way to shrink down the height (Should be enabled when autoSize is set to true)
